server:
  port: 8080
#  servlet:
#    context-path: /job-portal

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/recruitment_web"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: quochuy2k2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true